name: dotnetcore-build

on:
    workflow_dispatch:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main, develop ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
        dotnet-quality: 'ga'

    - name: Install dependencies
      run: dotnet restore RulesEngine.sln
    
    - name: Build
      run: dotnet build RulesEngine.sln --configuration Debug --no-restore
    
    - name: Test
      run: dotnet test RulesEngine.sln --collect:"XPlat Code Coverage" --no-build --configuration Debug --verbosity m
    
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.3.7
      with:
        reports: tests\*\TestResults\*\coverage.cobertura.xml
        targetdir: coveragereport
        reporttypes: Html;Cobertura;lcov
    
    - name: Check Coverage
      shell: pwsh
      run: ./scripts/check-coverage.ps1 -reportPath coveragereport/Cobertura.xml -threshold 80
    
    #- name: Coveralls GitHub Action
    #  uses: coverallsapp/github-action@v2.2.1
    #  if: ${{ github.event_name == 'push' }}
    #  with:
    #    github-token: ${{ secrets.GITHUB_TOKEN }}
    #    path-to-lcov: ./coveragereport/lcov.info